version: '3.8'
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/rust:1-1-bullseye
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    ports:
      - "3000:3000"
    networks:
      - shared-network

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    networks:
      - shared-network

volumes:
  postgres-data:

networks:
  shared-network: